from typing import Union,Tuple
from pathlib import Path
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

class QuestionnaireAnalysis:
    """
    Reads and analyzes data generated by the questionnaire experiment.
    Should be able to accept strings and pathlib.Path objects.
    """
    
    def __init__(self, data_fname: Union[pathlib.Path, str]):
        if not self.data_fname.exists():
            raise ValueError("Path does not exist")
        else:                  
            self.data_fname = data_fname

    def read_data(self):
        """
        Reads the json data located in self.data_fname into memory, to
        the attribute self.data.
        """
        with open(self.data_fname) as cur_file:
            df = pd.read_json(cur_file)
        return df
        

    def show_age_distrib(self):# -> Tuple[np.ndarray, np.ndarray]:
        """
        Calculates and plots the age distribution of the participants.
        Returns a tuple containing two numpy arrays:
        The first item being the number of people in a given bin.
        The second item being the bin edges.
        """
        df = self.read_data()
        age = df['age']
        dist = plt.hist(age)
        plt.title("Age Distribution")
        plt.show(dist)
       
        return dist[0:2]

        

    def remove_rows_without_mail(self) -> pd.DataFrame:
        """
        Checks self.data for rows with invalid emails, and removes them.
        Returns the corrected DataFrame, i.e. the same table but with
        the erroneous rows removed and the (ordinal) index after a reset.
        """        
        df = self.read_data()
        df['valid_1'] = (df['email'].str.find('@'))
        df['valid_2'] = (df['email'].str.find('.com'))
        df = df[df.valid_1 != -1]
        df = df[df.valid_2 != -1]
        df.pop('valid_1')
        df.pop('valid_2')
        df =df.reset_index(drop=True)

        return df

    def fill_na_with_mean(self) -> Union[pd.DataFrame, np.ndarray]:
        """
        Finds, in the original DataFrame, the subjects that didn't answer
        all questions, and replaces that missing value with the mean of the
        other grades for that student. Returns the corrected DataFrame,
        as well as the row indices of the students that their new grades
        were generated.
        """
        df1 =  self.data.loc[:,'q1':'q5']
        row_num= pd.isnull( self.data.loc[:,'q1':'q5']).any(1).to_numpy().nonzero()[0]
        df1 = df1.apply(lambda row: row.fillna(row.mean()), axis=1)
        self.data.update(df1)
        return (self.data,row_num)

 


if __name__ == '__main__':

   file_name = './data.json'
   quest = QuestionnaireAnalysis(file_name)

   print(f"""data:
   {quest.read_data()}
   age distrubution:
   {quest.show_age_distrib()}
   remove_rows_without_mail:
   {quest.remove_rows_without_mail()}
   fill_na_with_mean:
   {quest.fill_na_with_mean()}""")